### ISSUE TITLE
The performance of Pretrained-3D-ViSNet

### ISSUE THREAD

**Issue by PierreHao** [microsoft/ViSNet#2]
Hi, thank you for your good job ViSNet. 
I have run your code with the model Pretrained_3D_ViSNet_ckpt_0.ckpt and Pretrained_3D_ViSNet_ckpt_1.ckpt on the valid set, but the performance is only about 0.091, which means the distilling works badly? Is there something wrong with the performance 0.091?

**Comment by v-shaoningli** [comment]
Great work! The Graphormer architecture is better for distillation because it can be adopted to both 2D and 3D graphs. Though current EGNNs have better results for 3D structures, they cannot be directly adopted to 2D graphs and hence are hard for distillation. Moreover, you can try the pre-training methods in [3DInfomax](https://proceedings.mlr.press/v162/stark22a.html) because I think a unified structure (graph transformer in your paper) is better.

**Comment by v-shaoningli** [comment]
As 3DInfomax mentioned,  "Our pre-training can also be understood from a contrastive distillation perspective where the student 2D network learns from the teacher 3D network to produce 3D information". And the pre-trained model can be fine-tuned for various downstream datasets/tasks (GEOM-DRUG or QM9).

**Comment by PierreHao** [comment]
> As 3DInfomax mentioned, "Our pre-training can also be understood from a **contrastive distillation** perspective where the student 2D network learns from the teacher 3D network to produce 3D information". And the pre-trained model can be fine-tuned for various downstream datasets/tasks (GEOM-DRUG or QM9).

Thank you for your suggestion. 3DInformax, GraphMVP and UnifiedMol are also great works, I have done some experiments with these methods, and maybe it needs more techniques to improve the result. 
Anyway, thanks for your reply and your ViSNet.
